---

- name: Template nginx.conf
  ansible.builtin.template:
    src: "{{ template }}/nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload nginx.service