---

- name: Reload nginx.service
  ansible.builtin.systemd_service:
    name: nginx.service
    state: reloaded
  become: true

- name: Restart & Reload nginx.service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: nginx.service
  become: true