---

- name: Get Desktop IP
  set_fact:
    desktop_ip: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  with_items: "{{ groups['desktop'][0] }}"

- name: Include vars from template
  ansible.builtin.include_vars:
    file: "{{ template }}/main.yml"

- name: Template nginx.conf
  ansible.builtin.template:
    src: "{{ template }}/nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload nginx.service